-- MySQL Script generated by MySQL Workbench
-- Mon May 21 00:41:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema findapet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `findapet` ;

-- -----------------------------------------------------
-- Schema findapet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `findapet` DEFAULT CHARACTER SET utf8 ;
USE `findapet` ;

-- -----------------------------------------------------
-- Table `findapet`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findapet`.`address` (
  `idaddress` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  PRIMARY KEY (`idaddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findapet`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findapet`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address_idaddress` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_address_idx` (`address_idaddress` ASC),
  CONSTRAINT `fk_user_address`
    FOREIGN KEY (`address_idaddress`)
    REFERENCES `findapet`.`address` (`idaddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findapet`.`lacation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findapet`.`lacation` (
  `idlacation` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  PRIMARY KEY (`idlacation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findapet`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findapet`.`animal` (
  `idanimal` INT NOT NULL AUTO_INCREMENT,
  `race` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `size` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `user_iduser` INT NOT NULL,
  `lacation_idlacation` INT NOT NULL,
  PRIMARY KEY (`idanimal`),
  INDEX `fk_animal_user1_idx` (`user_iduser` ASC),
  INDEX `fk_animal_lacation1_idx` (`lacation_idlacation` ASC),
  CONSTRAINT `fk_animal_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `findapet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_lacation1`
    FOREIGN KEY (`lacation_idlacation`)
    REFERENCES `findapet`.`lacation` (`idlacation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findapet`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findapet`.`images` (
  `idimages` INT NOT NULL AUTO_INCREMENT,
  `image` MEDIUMBLOB NULL,
  `animal_idanimal` INT NOT NULL,
  PRIMARY KEY (`idimages`),
  INDEX `fk_images_animal1_idx` (`animal_idanimal` ASC),
  CONSTRAINT `fk_images_animal1`
    FOREIGN KEY (`animal_idanimal`)
    REFERENCES `findapet`.`animal` (`idanimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
